import time
import openai
import configparser
from playwright.sync_api import sync_playwright


class InstagramBot:
    def __init__(self, config_path='config.ini'):
        # Load configuration from config.ini
        self.config = configparser.ConfigParser()
        self.config.read(config_path)

        # OpenAI setup
        openai.api_key = self.config['openai']['api_key']

        # Instagram credentials
        self.instagram_username = self.config['instagram']['username']
        self.instagram_password = self.config['instagram']['password']

    # Function to get the response from OpenAI (ChatGPT)
    def generate_response(self, message):
        response = openai.Completion.create(
            engine="text-davinci-003",  # You can change the model as needed
            prompt=f"Reply to this Instagram message: {message}",
            max_tokens=50
        )
        return response.choices[0].text.strip()

    # Function to simulate typing
    def type_like_human(self, page, message, element_selector):
        for char in message:
            page.locator(element_selector).type(char)
            time.sleep(0.05)  # Simulate typing speed

    def login(self, page):
        # Navigate to Instagram and log in
        page.goto('https://www.instagram.com/')
        time.sleep(2)

        # Log in
        page.fill('input[name="username"]', self.instagram_username)
        page.fill('input[name="password"]', self.instagram_password)
        page.click('button[type="submit"]')
        time.sleep(5)  # Wait for the login to complete

    def check_inbox_and_reply(self):
        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(headless=False)  # Set to True if you want headless
            page = browser.new_page()

            # Log in to Instagram
            self.login(page)

            # Go to Instagram inbox
            page.goto('https://www.instagram.com/direct/inbox/')
            time.sleep(5)

            # Check for messages that are "5m" old
            while True:
                # Find messages that are 5 minutes old
                messages = page.locator('span:has-text("5m")')  # Selector to find messages that are 5 minutes old
                if messages.count() > 0:
                    messages.first.click()
                    time.sleep(2)  # Wait for message to open

                    # Read the last message text
                    last_message = page.locator('div[role="textbox"]').last.text_content()
                    print(f"Last message received: {last_message}")

                    # Send the message to OpenAI to generate a response
                    reply = self.generate_response(last_message)
                    print(f"Reply generated by OpenAI: {reply}")

                    # Type the reply like a human
                    message_input_selector = 'textarea[placeholder="Message..."]'  # Adjust this if the selector changes
                    self.type_like_human(page, reply, message_input_selector)

                    # Send the message
                    page.locator('button[type="submit"]').click()

                    # Break the loop after responding
                    break

                # Wait for some time before checking again
                time.sleep(60)  # Check every minute

            # Close the browser
            browser.close()


# Entry point to run the bot
if __name__ == "__main__":
    bot = InstagramBot()
    bot.check_inbox_and_reply()
